version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6-browsers
    steps:
      - checkout
      - run:
          name: install
          command: npm install
      - run:
          name: build
          command: npm ng -- build --prod --aot --no-progress
      - run:
          name: test
          command: npm ng -- test --sr --no-progress
