version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:6-browsers
    steps:
      - checkout
      - restore-cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install dependencies
          command: yarn install
      - run:
          name: build
          command: yarn ng build --prod --aot --no-progress
      - run:
          name: test
          command: yarn ng test --sr --no-progress
      - run:
          name: lint
          command: yarn ng lint
      - save-cache:
          key: dependency-cache-{{ checksum "package.json"}}
          paths:
            - node_modules
