version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:6-browsers
    steps:
      - checkout
      - run:
          name: install dependencies
          command: npm install
      - run:
          name: build
          command: ng build --prod --aot --no-progress
      - run:
          name: test
          command: ng test --sr --no-progress
      - run:
          name: lint
          command: ng lint
